name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
commitish: release # release 브랜치를 기준으로 설정(default: main)
categories:
  - title: '🎁 새로운 기능이 추가되었어요'
    label: '🎁 feature'
  - title: '🐞 자잘한 버그를 수정했어요'
    label: '🔨 fix'
  - title: '🐬 코드를 개선했어요'
    label:
      - '📋 docs'
      - '🧼 refactor'
      - '🪄 chore'
      - '🎫 test'
      - '❌ remove'
change-template: '- $TITLE @$AUTHOR (#$NUMBER) '
change-title-escapes: '\<*_&'
template: |
  ## 이번 버전의 변경사항은 아래와 같아요
  ---
  $CHANGES
no-changes-template: '변경사항이 없어요'
version-resolver:
  major:
    labels:
      - '✨ major'
  minor:
    labels:
      - '✨ minor'
  patch:
    labels:
      - '✨ patch'
  default: patch