ALTER TABLE routine_infov2
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL,
    ADD COLUMN deleted_at DATETIME(6)  NULL DEFAULT NULL;

ALTER TABLE routinev2
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL,
    ADD COLUMN deleted_at DATETIME(6) NULL DEFAULT NULL;