name: Deploy Prometheus to Amazon ECS

on:
  push:
    branches: ["release", "develop"]
    paths:
      - "config/dev/application-prometheus-dev.yml"
      - "config/prod/application-prometheus-prod.yml"
      - "prometheus/**"

jobs:
  deploy-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "ECR_REPO=${{ secrets.ECR_REPO_PROMETHEUS_DEV }}" >> $GITHUB_ENV
            echo "CONFIG_FILE=config/dev/application-prometheus-dev.yml" >> $GITHUB_ENV
            echo "SERVICE_NAME=${{ secrets.ECS_SERVICE_PROMETHEUS_DEV }}" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
            echo "ECR_REPO=${{ secrets.ECR_REPO_PROMETHEUS_PROD }}" >> $GITHUB_ENV
            echo "CONFIG_FILE=config/prod/application-prometheus-prod.yml" >> $GITHUB_ENV
            echo "SERVICE_NAME=${{ secrets.ECS_SERVICE_PROMETHEUS_PROD }}" >> $GITHUB_ENV
          fi

      - name: Build and Push Prometheus Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cp ${{ env.CONFIG_FILE }} ./prometheus.yml
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG \
                       -t $ECR_REGISTRY/${{ env.ECR_REPO }}:${{ env.ENV }} .
          docker push $ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.ECR_REPO }}:${{ env.ENV }}

      - name: Update ECS Prometheus Service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
                                 --service ${{ env.SERVICE_NAME }} \
                                 --force-new-deployment