name: Draft new release
on:
  workflow_run:
    workflows: [ "Deploy to Amazon ECS" ] # ecs 배포 워크플로우가 완료된 후 실행
    types:
      - completed
  push:
    branches:
      - release # release 브랜치에 푸시될 때 실행
jobs:
  build:
    #
    if: ${{ github.event.workflow_run.conclusion == 'success'}} # 이전 워크플로우가 성공적으로 완료된 경우에만 실행
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        # reference : https://github.com/release-drafter/release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}